services:
  - type: web
    name: quizroom-server
    env: node
    rootDir: .
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 3005
